# Generated by Django 2.0.2 on 2018-02-20 02:46

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
